CleanStudentManagement.UI/CleanStudentManagement.UI/Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CleanStudentManagement.BLL.Services;
using CleanStudentManagement.Data;
using CleanStudentManagement.Models;
using CleanStudentManagement.UI.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CleanStudentManagement.UI.Controllers
{
    [RoleAuthorize(2)]
    public class ExamsController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IExamService _examService;
        private readonly ApplicationDbContext _context;

        public ExamsController(IGroupService groupService, IExamService examService, ApplicationDbContext context)
        {
            _groupService = groupService;
            _examService = examService;
            _context = context;
        }

        public IActionResult Index(int pageNumber = 1, int pageSize = 10)
        {

            return View(_examService.GetAll(pageNumber, pageSize));
        }
        [HttpGet]
        public IActionResult Create()
        {
            var groups = _groupService.GetAllGroups();
            ViewBag.AllGroups = new SelectList(groups, "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateExamsViewModel vm)
        {
            _examService.AddExam(vm);
            return RedirectToAction("Index");
        }


    }
}

CleanStudentManagement.UI/CleanStudentManagement.UI/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CleanStudentManagement.BLL.Services;
using CleanStudentManagement.Data;
using CleanStudentManagement.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CleanStudentManagement.UI.Controllers
{
    public class GroupsController : Controller
    {
        private IGroupService _groupService;
        private IStudentService _studentService;
        private readonly ApplicationDbContext _context;

        public GroupsController(IGroupService groupService, IStudentService studentService, ApplicationDbContext context)
        {
            _groupService = groupService;
            _studentService = studentService;
            _context = context;
        }

        public IActionResult Index(int pageNumber = 1, int pageSize = 10)
        {
            return View(_groupService.GetAll(pageNumber, pageSize));
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(GroupViewModel viewModel)
        {
            var vm = _groupService.Addgroup(viewModel);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            GroupStudentViewModel vm = new GroupStudentViewModel();
            var group = _groupService.GetGroup(id);
            var students = _studentService.GetAll();
            vm.GroupId = group.Id;
            foreach (var student in students)
            {
                vm.StudentList.Add(new CheckBoxTable
                {
                    Id = student.Id,
                    Name = student.Name,
                    IsChecked = student.GroupsId == null? false: true

                });
            }
            return View(vm);


        }
        [HttpPost]
        public IActionResult Details(GroupStudentViewModel viewModel)
        {
            bool result = _studentService.SetGroupIdToStudent(viewModel);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(viewModel);

        }
    }
}

CleanStudentManagement.UI/CleanStudentManagement.UI/Controllers/QnAsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CleanStudentManagement.BLL.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CleanStudentManagement.Models;
using CleanStudentManagement.Data;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CleanStudentManagement.UI.Controllers
{
    public class QnAsController : Controller
    {
        private IExamService _examService;
        private IQnAsService _iqnAsService;
        private readonly ApplicationDbContext _context;

        public QnAsController(IExamService examService, IQnAsService iqnAsService, ApplicationDbContext context)
        {
            _examService = examService;
            _iqnAsService = iqnAsService;
            _context = context;
        }

        public IActionResult Index(int pageNumber = 1, int pageSize = 10)
        {
            var qnAs = _iqnAsService.GetAll(pageNumber, pageSize);
            return View(qnAs);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var exams = _examService.GetAllExams();
            ViewBag.examsList = new SelectList(exams, "Id", "Title");
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateQnAsViewModel viewModel)
        {
            _iqnAsService.AddQnAs(viewModel);
            return RedirectToAction("Index");
        }

    }
}

CleanStudentManagement.UI/CleanStudentManagement.UI/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CleanStudentManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using CleanStudentManagement.BLL.Services;
using CleanStudentManagement.Data;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CleanStudentManagement.UI.Controllers
{
    public class StudentsController : Controller
    {
        private IStudentService _studentService;
        private IExamService _examService;
        private IQnAsService _qnasService;
        private string containerName = "StudentImage";
        private string cvContainerName = "StudentCV";
        private readonly ApplicationDbContext _context;

        private IUtilityService _utilityService;

        public StudentsController(IStudentService studentService, IExamService examService, IQnAsService qnasService, ApplicationDbContext context)
        {
            _studentService = studentService;
            _examService = examService;
            _qnasService = qnasService;
            _context = context;
            // _utilityService = utilityService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Profile()
        {
            var sessionObj = HttpContext.Session.GetString("loginDetails");
            if (sessionObj != null)
            {
                var loginViewModel = JsonConvert.DeserializeObject<LoginViewModel>(sessionObj);
                var studentDetails = _studentService.GetStudentById(loginViewModel.Id);
                return View(studentDetails);
            }
            return RedirectToAction("Login", "Accounts");
        }
        [HttpPost]
        public async Task<IActionResult> Profile(StudentProfileViewModel vm)
        {
            if (vm.ProfilePictureUrl != null)
                vm.ProfilePicture = await _utilityService.SaveImage(containerName, vm.ProfilePictureUrl);
            if (vm.CvFileUrl != null)
                vm.CVFileName = await _utilityService.SaveImage(cvContainerName, vm.CvFileUrl);

            _studentService.UpdateProfile(vm);
            return RedirectToAction("profile");

        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateStudentViewModel vm)
        {
            var success = await _studentService.AddStudentAsync(vm);
            if (success > 0)
            {
                return RedirectToAction("Index");
            }
            return View(vm);
        }
        public IActionResult Index(int pageNumber = 1, int pageSize = 10)
        {

            return View(_studentService.GetAllStudents(pageNumber, pageSize));
        }
        [HttpGet]
        public IActionResult AttendExam()
        {
            var model = new AttendExamViewModel();
            string loginObj = HttpContext.Session.GetString("loginDetails");
            LoginViewModel sessionObj = JsonConvert.DeserializeObject<LoginViewModel>(loginObj);
            if (sessionObj != null)
            {
                model.StudentId = sessionObj.Id;
                var todayExam = _examService.GetAllExams().
                Where(x => x.StartDate.Date == DateTime.Today.Date).FirstOrDefault();
                if (todayExam == null)
                {
                    model.Message = "No Exam Scheduled today";
                    return View(model);
                }
                else
                {
                    if (!_qnasService.IsAttendExam(todayExam.Id, model.StudentId))
                    {
                        model.QnAsList = _qnasService.GetAllByExamId(todayExam.Id).ToList();
                        model.ExamName = todayExam.Title;
                        model.Message = "";
                        return View(model);
                    }
                    else
                    {
                        model.Message = "You have already attend this exam";
                        return View(model);
                    }
                }
            }
            return RedirectToAction("Login", "Accounts");
        }
        [HttpPost]
        public IActionResult AttendExam(AttendExamViewModel viewModel)

        {
            bool result = _studentService.SetExamResult(viewModel);
            return RedirectToAction("");

        }
        public IActionResult Result()
        {
            var sessionObj = HttpContext.Session.GetString("loginDetails");
            if (sessionObj != null)
            {
                var loginViewModel = JsonConvert.DeserializeObject<LoginViewModel>(sessionObj);
                var model = _studentService.GetExamResults(Convert.ToInt32(loginViewModel.Id));
                return View(model);

            }
            return RedirectToAction("Login", "Accounts");
        }
    }
}

CleanStudentManagement.UI/CleanStudentManagement.UI/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json;
@inject IHttpContextAccessor HttpContextAccessor




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleanStudentManagement.UI</title>
    <link rel="stylesheet" href="~/css/vapor.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanStudentManagement.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @if (HttpContextAccessor.HttpContext.Session.GetString("loginDetails") != null)
        {
            var sessionObj = HttpContextAccessor.HttpContext.Session.GetString("loginDetails");
            var loginDetails = JsonConvert.DeserializeObject<CleanStudentManagement.Models.LoginViewModel>(sessionObj);
            @if (loginDetails.Role == 1)
            {
                <partial name="_adminnav" />
            }
            @if (loginDetails.Role == 2)
            {
                <partial name="_teachernav" />
            }
            @if (loginDetails.Role == 3)
            {
                <partial name="_studentnav" />
            }
        }
        else
        {
            <partial name="_defaultnav" />
        }





    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CleanStudentManagement.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CleanStudentManagement.UI/CleanStudentManagement.UI/Views/Shared/_adminnav.cshtml
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Admin CMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" asp-action="Index" asp-controller="Home">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="users">Teachers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Students">Students</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Groups">Classes</a>
                </li>

                @*
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li> *@
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

CleanStudentManagement.UI/CleanStudentManagement.UI/Views/Shared/_defaultnav.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Management</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>

            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

CleanStudentManagement.UI/CleanStudentManagement.UI/Views/Shared/_studentnav.cshtml
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Student CMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="students" asp-action="profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="students" asp-action="AttendExam">Attend Exam</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="students" asp-action="Result">Result</a>
                </li>
                @*  <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li> *@
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

CleanStudentManagement.UI/CleanStudentManagement.UI/Views/Shared/_teachernav.cshtml
<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Teacher CMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Exams" asp-action="Index">Exam</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="QnAs" asp-action="Index">QnAs</a>
                </li>
                @* <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li> *@
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>